plugin/src/main/kotlin/motif/intellij/graph/GraphProcessor.kt, plugin/src/main/kotlin/motif/intellij/psi/PsiExt.kt
Fix ClassCastException in the plugin by ensuring correct type casting. Fixes #7
=> Fix Plugin ClassCastException

compiler/src/main/java/motif/compiler/ir/CompilerClass.kt, it/src/main/java/testcases/T044_static_objects_method/Scope.java, it/src/main/java/testcases/T044_static_objects_method/Test.java, plugin/src/main/kotlin/motif/intellij/validation/ir/IntelliJClass.kt
=> Recognize static Objects methods as valid factory methods.

compiler/src/main/java/motif/compiler/errors/parsing/NullableDependencyHandler.kt, compiler/src/main/java/motif/compiler/errors/parsing/NullableFactoryMethodHandler.kt
=> Suggest Optional as an alternative to nullable dependencies.

plugin/build.gradle, plugin/src/main/kotlin/motif/intellij/validation/ir/IntelliJClass.kt, plugin/src/main/kotlin/motif/intellij/validation/ir/IntelliJMethod.kt, plugin/src/main/kotlin/motif/intellij/validation/ir/IntelliJMethodParameter.kt, plugin/src/main/kotlin/motif/intellij/validation/ir/IntelliJType.kt, plugin/src/test/kotlin/motif/intellij/validation/ir/IrTest.kt
Handle method inheritance and generics correctly.
=> IntelliJ Plugin: Handle generics

README.md
=> YouTube link was broken, updated the link to the latest video.

compiler/src/main/java/motif/compiler/errors/validation/NotExposedDynamicHandler.kt, compiler/src/main/java/motif/compiler/errors/validation/NotExposedHandler.kt, lib/src/main/java/motif/Expose.java
Add fix suggestions to NotExposed* error messages and link to documentation.
=> Improve "NotExposed" error messages.

README.md
Since the README shows up at the top level, it's bet to link to the folder, otherwise I have to navigate back up to see the plugin code.
=> Minor update to link

tests/build.gradle, tests/compiler/build.gradle, tests/compiler/src/main/java/motif/stubcompiler/StubProcessor.kt
Remove `:test:compiler` dependency on `core` and `compiler`.
=> Remove unnecessary dependencies.

compiler/src/main/java/motif/compiler/errors/ErrorHandler.kt, compiler/src/main/java/motif/compiler/errors/parsing/NullableSpreadMethodHandler.kt, core/src/main/kotlin/motif/models/errors/MotifError.kt, core/src/main/kotlin/motif/models/parsing/ObjectsClassParser.kt, tests/src/main/java/testcases/E041_nullable_spread_method/Scope.java, tests/src/main/java/testcases/E041_nullable_spread_method/Spreadable.java, tests/src/main/java/testcases/E041_nullable_spread_method/Test.java, tests/src/main/java/testcases/T050_spreadable_with_nullable/Scope.java, tests/src/main/java/testcases/T050_spreadable_with_nullable/Spreadable.java, tests/src/main/java/testcases/T050_spreadable_with_nullable/Test.java
**Description**: Added check for @Spread classes with nullable methods
**Related issue(s)**: #66
=> Added check for @Spread classes with nullable methods

tests/src/main/java/testcases/T059_default_objects_methods/Scope.java, tests/src/main/java/testcases/T059_default_objects_methods/Test.java, tests/src/main/java/testcases/T060_default_objects_methods2/IntObjects.java, tests/src/main/java/testcases/T060_default_objects_methods2/Scope.java, tests/src/main/java/testcases/T060_default_objects_methods2/StringObjects.java, tests/src/main/java/testcases/T060_default_objects_methods2/Test.java
Add test coverage for inherited default interface factory methods.
=> Add tests for default interface factory methods.

compiler2/src/main/kotlin/motif/compiler/ScopeImpl.kt
The new code generation implementation loaded more classes than necessary. Before this change, we were loading the dependencies required by all Scopes, even if the corresponding ScopeImpl had already been generated by by a previous compilation pass. The PR updates the new code generation logic to only load Scope dependency classes when necessary.
=> Only load generated dependency classes for existing ScopeImpls if needed

core/src/main/kotlin/motif/core/ResolvedGraph.kt, core/src/main/kotlin/motif/core/State.kt, errormessage/src/main/kotlin/motif/errormessage/NodeHandler.kt, models/src/main/kotlin/motif/models/Dependencies.kt, models/src/main/kotlin/motif/models/FactoryMethod.kt, models/src/main/kotlin/motif/models/Node.kt, models/src/main/kotlin/motif/models/Scope.kt, models/src/main/kotlin/motif/models/ScopeMethod.kt, tests/src/main/java/testcases/E005_dependencies_cycle/ERROR.txt, tests/src/main/java/testcases/E006_dependencies_cycle_2/ERROR.txt, tests/src/main/java/testcases/E025_dependency_cycle_3/ERROR.txt, tests/src/main/java/testcases/E050_unsatisfied_dependency_no_duplicates/Child.java, tests/src/main/java/testcases/E050_unsatisfied_dependency_no_duplicates/ERROR.txt, tests/src/main/java/testcases/E050_unsatisfied_dependency_no_duplicates/Grandchild.java, tests/src/main/java/testcases/E050_unsatisfied_dependency_no_duplicates/Scope.java, tests/src/main/java/testcases/T063_diamond_expose_to_grandchild/ChildA.java, tests/src/main/java/testcases/T063_diamond_expose_to_grandchild/ChildB.java, tests/src/main/java/testcases/T063_diamond_expose_to_grandchild/GrandChild.java, tests/src/main/java/testcases/T063_diamond_expose_to_grandchild/Scope.java, tests/src/main/java/testcases/T063_diamond_expose_to_grandchild/Test.java, tests/src/main/java/testcases/T064_diamond_child_parameter_override/Child1.java, tests/src/main/java/testcases/T064_diamond_child_parameter_override/Child2.java, tests/src/main/java/testcases/T064_diamond_child_parameter_override/GrandChild.java, tests/src/main/java/testcases/T064_diamond_child_parameter_override/Scope.java, tests/src/main/java/testcases/T064_diamond_child_parameter_override/Test.java, tests/src/main/java/testcases/T065_diamond_hide_source/Child1.java, tests/src/main/java/testcases/T065_diamond_hide_source/Child2.java, tests/src/main/java/testcases/T065_diamond_hide_source/GrandChild.java, tests/src/main/java/testcases/T065_diamond_hide_source/Scope.java, tests/src/main/java/testcases/T065_diamond_hide_source/Test.java
* Refactor graph resolution logic to be more maintainable.
* Add Source/Sink information directly to Motif AST models. This will make IDE feature implementation simpler.
=> Refactor graph resolution logic

intellij/src/main/kotlin/motif/intellij/MotifPanel.kt
**This PR just for visibility and is not production code. It will be merged into the intellij-prototype branch.**
Load PsiClasses and compute DI graph in the background so we don't block the UI on refresh.
=> IntelliJ Plugin Load graph in the background

ast/src/main/kotlin/motif/ast/IrClass.kt, compiler/ast/build.gradle, compiler/ast/src/main/kotlin/motif/ast/compiler/CompilerClass.kt, compiler/ast/src/test/kotlin/motif/ast/compiler/CompilerClassTest.kt, intellij/ast/src/main/kotlin/motif/ast/intellij/IntelliJClass.kt, intellij/ast/src/main/kotlin/motif/ast/intellij/IntelliJType.kt, intellij/ast/src/test/kotlin/motif/ast/intellij/IntelliJClassTest.kt
=> Add superclass and typeArguments fields to IrClass

tests/src/main/java/testcases/T003_multiple_dependencies/GRAPH.txt, tests/src/main/java/testcases/T011_inheritence_scope/GRAPH.txt, tests/src/main/java/testcases/T012_inheritence_objects/GRAPH.txt, tests/src/main/java/testcases/T017_spread/GRAPH.txt, tests/src/main/java/testcases/T018_spread_inheritence/GRAPH.txt, tests/src/main/java/testcases/T020_naming_collisions/GRAPH.txt, tests/src/main/java/testcases/T034_dagger_as_parent/GRAPH.txt, tests/src/main/java/testcases/T036_dagger_spread/GRAPH.txt, tests/src/main/java/testcases/T040_keywords/GRAPH.txt, tests/src/main/java/testcases/T042_bind_qualified/GRAPH.txt, tests/src/main/java/testcases/T046_spread_static_spreadable_method/GRAPH.txt, tests/src/main/java/testcases/T048_expose_spread_factory_method/GRAPH.txt, tests/src/main/java/testcases/T049_binds_primitive/GRAPH.txt, tests/src/main/java/testcases/T050_spreadable_with_nullable/GRAPH.txt, tests/src/main/java/testcases/T054_binds_wildcards/GRAPH.txt, tests/src/main/java/testcases/T055_binds_upcast/GRAPH.txt, tests/src/main/java/testcases/T060_default_objects_methods2/GRAPH.txt, viewmodel/src/main/kotlin/motif/viewmodel/GraphViewModel.kt
Ensure collections in view models have stable ordering. Right now view models are only used for tests so this does not affect production code.
=> Stable ordering for view models

compiler/build.gradle, compiler/src/test/java/motif/compiler/ProGuard.kt, compiler/src/test/java/motif/compiler/TestHarness.java, compiler/src/test/resources/default.pro, gradle/dependencies.gradle
Run integration tests with ProGuard enabled.
=> Integration test suite runs with ProGuard enabled

CHANGELOG.md, errormessage/src/main/kotlin/motif/errormessage/AccessMethodParametersHandler.kt, errormessage/src/main/kotlin/motif/errormessage/ErrorHandler.kt, errormessage/src/main/kotlin/motif/errormessage/VoidScopeMethodHandler.kt, models/src/main/kotlin/motif/models/ParsingError.kt, models/src/main/kotlin/motif/models/ScopeMethod.kt, tests/src/main/java/testcases/E027_invalid_scope_method/ERROR.txt, tests/src/main/java/testcases/E028_invalid_scope_method_2/ERROR.txt
=> Improve invalid Scope method error messages.

intellij/src/main/kotlin/motif/intellij/ChildChangeListener.kt, intellij/src/main/kotlin/motif/intellij/GraphFactory.kt, intellij/src/main/kotlin/motif/intellij/GraphManager.kt, intellij/src/main/kotlin/motif/intellij/MotifPanel.kt
Very basic UI to show Scope graph.
=> Base IntelliJ functionality

README.md
=> Implementation instead of deprecated compile

intellij/src/main/kotlin/motif/intellij/hierarchy/ScopePropertyHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySinkDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySinkDetailsDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySinksSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourceDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourceDetailsDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourcesSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyUsageSinksSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyUsageSourcesSectionDescriptor.kt
- fix keyboard navigation
- remove legend code
- remove unecessary icons in property hierarchy
- Add @Expose / Provided By / Consumed By labels
=> Misc UI cleanup/improvements

intellij/src/main/kotlin/motif/intellij/ScopeHierarchyUtils.kt, intellij/src/main/kotlin/motif/intellij/actions/MotifGraphAction.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyTreeStructure.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopePropertyHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyScopeDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySinkDetailsDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourceDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourceDetailsDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourcesSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/provider/ScopeHierarchyLineMarkerProvider.kt, intellij/src/main/kotlin/motif/intellij/ui/MotifErrorPanel.kt, intellij/src/main/resources/META-INF/plugin.xml
- Fix Error pane clipping
- Get rid of lock icon in scope hierarchy view
- Hide source when it's a dynamic dependency or scope
- Auto expand scope properties
- User supertype icon
- Verify lazy graph computation
=> Minor UI improvements

intellij/src/main/kotlin/motif/intellij/MotifToolWindowFactory.kt, intellij/src/main/kotlin/motif/intellij/ScopeHierarchyUtils.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyTreeStructure.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyDependencyDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyRootErrorDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyScopeDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySinkDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySinkDetailsDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourceDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourceDetailsDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourcesAndSinksSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/provider/ScopeNavigationLineMarkerProvider.kt
- Implement lisdt sorting 
- Use package instead of fully qualified name
- Error shouldn’t be closable and should display error #
- Root scope should not offer upward navigation to parent scope
- Sink nodes should link to scope 
- Disambiguate sinks with -> label
=> Addition fixes in preparation for Alpha release

intellij/build.gradle, intellij/src/main/resources/META-INF/plugin.xml
=> Update plugin email adress + bump version

intellij/build.gradle, intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/actions/MotifGraphAction.kt, intellij/src/main/kotlin/motif/intellij/actions/MotifUsageAction.kt, intellij/src/main/kotlin/motif/intellij/analytics/AnalyticsProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/analytics/MotifAnalyticsActions.kt, intellij/src/main/kotlin/motif/intellij/analytics/MotifAnalyticsLogger.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/provider/ScopeHierarchyLineMarkerProvider.kt, intellij/src/main/kotlin/motif/intellij/provider/ScopeNavigationLineMarkerProvider.kt, intellij/src/main/resources/META-INF/plugin.xml
- extension point for doing custom logging of user interaction with plugin
=> Add support for basic logging via extension point

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/analytics/MotifAnalyticsActions.kt
We should be logging basic graph computation error in our initial logging.
=> Add logs for motif graph errors

intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopePropertyHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourceDescriptor.kt
- add help/file a bug button to main scope pane
- fix (rare) threading issue when refreshing scopes
- update UI for @Expose (this piece is not searchable)
=> Add help/bug button and fix minor issues

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/actions/MotifAncestorGraphAction.kt, intellij/src/main/kotlin/motif/intellij/analytics/MotifAnalyticsActions.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/HierarchyBrowserBase.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopePropertyHierarchyBrowser.kt, intellij/src/main/resources/META-INF/plugin.xml
This PR adds a 'Show Graph' contextual menu item which is active at all time, regardless of the editor caret position / highlighted item.
=> Add additional menu item for tool discoverability

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt
Fix "Please wait" error message stuck when failure occurs.
=> Better handling of graph computation error

gradle/dependencies.gradle
See https://github.com/square/kotlinpoet/releases/tag/1.9.0
=> KotlinPoet 1.9.0

.github/workflows/ci.yml
Fix duplicated `./gradlew` call
=> Fix snapshot upload script

.github/workflows/ci.yml
Sorry for all the noise. This time I tested the CI in my fork, so it should be good now
=> Fix credential properties names for snapshot publish task

.github/workflows/ci.yml
=> Remove closeAndReleaseRepository task for the snapshot publish step.

samples/sample-kotlin/src/main/java/motif/sample/MainActivity.kt, samples/sample-kotlin/src/main/java/motif/sample/MainScope.kt
=> Use ScopeFactory in the kotlin example

gradle/dependencies.gradle, samples/sample-kotlin/build.gradle, samples/sample-kotlin/src/main/res/layout/activity_main.xml
Bump Kotlin, KotlinPoet, and Room to latest compatible versions
=> Bump Kotlin, KotlinPoet, and Room

compiler/src/test/java/motif/compiler/NamesTest.kt
Add coverage for arrays and enums
=> Increase coverage for NameTest

.github/workflows/ci.yml, gradle/dependencies.gradle, samples/sample-lib-ksp/build.gradle
Update Kotlin & KSP ([release notes](https://github.com/google/ksp/releases/tag/1.7.20-1.0.8)) to fix #249
=> Update to Kotlin 1.7.20 & KSP 1.0.8

gradle/dependencies.gradle
Move off the alpha version of XProcessing
=> XProcessing to v2.5.0 & KotlinPoet to v1.12.0

lib/build.gradle
Set version 1.8 since thats what the main apps use and we want to be compat when using Gradle module metadata
=> Set JVM version to 1.8

CHANGELOG.md, gradle.properties, gradle/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, samples/sample/build.gradle
Prepare for release 0.4.0-alpha08
I had to update the following three plugins to build the release
- org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin
- gradle
- com.vanniktech:gradle-maven-publish-plugin
=> Prepare for release 0.4.0-alpha08
