build.gradle, compiler/build.gradle
Set buildscript in root project instead.
This is the more conventional way of modifying the buildscript for
gradle projects.
=> Don't reconfigure buildscript for every project.

plugin/src/main/kotlin/motif/intellij/MotifScopeLineMarkerProvider.kt
Add check in `MotifScopeLineMarkerProvider#collectNavigationMarkers` to add navigation markers only if the containing class is a Motif Scope. Fixes #8
=> Add Scope Navigation Icons only in Motif Scope Classes

compiler/src/main/java/motif/compiler/errors/ErrorHandler.kt, compiler/src/main/java/motif/compiler/errors/validation/NotExposedDynamicHandler.kt, it/src/main/java/testcases/E011_dynamic_dependency_not_exposed/Child.java, it/src/main/java/testcases/E011_dynamic_dependency_not_exposed/Grandchild.java, it/src/main/java/testcases/E011_dynamic_dependency_not_exposed/Scope.java, it/src/main/java/testcases/E011_dynamic_dependency_not_exposed/Test.java, it/src/main/java/testcases/T045_dynamic_dependency_expose/Child.java, it/src/main/java/testcases/T045_dynamic_dependency_expose/Grandchild.java, it/src/main/java/testcases/T045_dynamic_dependency_expose/Scope.java, it/src/main/java/testcases/T045_dynamic_dependency_expose/Test.java, models/src/main/kotlin/motif/models/errors/MotifError.kt, models/src/main/kotlin/motif/models/errors/MotifErrors.kt, models/src/main/kotlin/motif/models/graph/Graph.kt, models/src/main/kotlin/motif/models/graph/Node.kt, models/src/main/kotlin/motif/models/motif/ScopeClass.kt, models/src/main/kotlin/motif/models/motif/dependencies/DynamicDependency.kt, models/src/main/kotlin/motif/models/motif/dependencies/RequiredDependencies.kt, models/src/main/kotlin/motif/models/parsing/ChildMethodParser.kt
Before this change, exposing a dynamic dependency to grandchildren (or further descendants) would require this pattern:
```java
@Scope
interface ParentScope {
ChildScope child(@Named("dynamic") String string);
@motif.Dependencies
interface Dependencies {}
}
@Scope
interface ChildScope {
GrandChildScope grandchild();
@motif.Objects
class Objects {
@Expose
String string(@Named("dynamic") String s);
}
}
@Scope
interface GrandChildScope {
String string();
}
```
To simplify this use case, this PR updates the API to allow annotating dynamic dependencies with `@Expose`:
```java
@Scope
interface ParentScope {
ChildScope child(@Expose String string);
@motif.Dependencies
interface Dependencies {}
}
@Scope
interface ChildScope {
GrandChildScope grandchild();
}
@Scope
interface GrandChildScope { …
```
=> Allow exposing dynamic dependencies with the @Expose annotation.

compiler/src/main/java/motif/compiler/codegen/JavaPoetUtil.kt, compiler/src/main/java/motif/compiler/codegen/Names.kt, compiler/src/test/java/motif/compiler/codegen/NamesTest.java
Fixes #35 
Given the following custom qualifier:
```java
@Qualifier @interface Foo {}
```
Here are the dependency names that will be generated:
|type|name|
|-|-|
| `@Foo String`                  | "fooString" |
| `@Named("bar") String` | "barString" |
=> Better names for qualified dependencies.

it/src/main/java/testcases/T046_spread_static_spreadable_method/Scope.java, it/src/main/java/testcases/T046_spread_static_spreadable_method/Spreadable.java, it/src/main/java/testcases/T046_spread_static_spreadable_method/Test.java
Fixes #44 
Static methods should also be spreadable. Add a test to verify this behavior.
=> Add test for static spreadable method

compiler/src/main/java/motif/compiler/codegen/ChildMethodFactory.kt, it/src/main/java/testcases/E036_no_suitable_constructor_interface/Foo.java, it/src/main/java/testcases/E036_no_suitable_constructor_interface/Scope.java, it/src/main/java/testcases/E036_no_suitable_constructor_interface/Test.java, it/src/main/java/testcases/T047_dynamic_dependency_named_component/Child.java, it/src/main/java/testcases/T047_dynamic_dependency_named_component/Scope.java, it/src/main/java/testcases/T047_dynamic_dependency_named_component/Test.java, models/src/main/kotlin/motif/models/parsing/ObjectsClassParser.kt
Fixes #46 #47 #48 #49 
- `@Spread ` only applies to methods
- Support dynamic dependencies named "component"
- Better error message for interface constructor factory method
=> Various Bug Fixes

it/src/main/java/testcases/E037_spread_not_exposed/Child.java, it/src/main/java/testcases/E037_spread_not_exposed/Scope.java, it/src/main/java/testcases/E037_spread_not_exposed/Spreadable.java, it/src/main/java/testcases/E037_spread_not_exposed/Test.java, it/src/main/java/testcases/T048_expose_spread_factory_method/Child.java, it/src/main/java/testcases/T048_expose_spread_factory_method/Scope.java, it/src/main/java/testcases/T048_expose_spread_factory_method/Spreadable.java, it/src/main/java/testcases/T048_expose_spread_factory_method/Test.java, models/src/main/kotlin/motif/models/motif/ScopeClass.kt
Previously we were auto-exposing all @Spread dependencies. Now correctly expose @Spread dependencies only when annotated with @Expose.
=> Handle @Expose + @Spread correctly.

compiler/src/main/java/motif/compiler/codegen/CodegenCache.kt, compiler/src/main/java/motif/compiler/codegen/ModuleFactory.kt, compiler/src/main/java/motif/compiler/codegen/ScopeImplFactory.kt, models/src/main/kotlin/motif/models/motif/objects/FactoryMethod.kt
Fixes #53
* Make Module static and abstract.
* Use `@BindsInstance` to provide `FooScope` instance.
* Call Objects methods statically if static.
```java
@motif.Scope
public interface FooScope {
@motif.Objects
class Objects {
static String s() {
return "s";
}
}
}
```
```java
@ScopeImpl(
children = {},
scope = FooScope.class,
dependencies = FooScopeImpl.Dependencies.class
)
public class FooScopeImpl implements FooScope {
private final Component component;
public FooScopeImpl(Dependencies dependencies) {
this.component = DaggerFooScopeImpl_Component.builder()
.dependencies(dependencies)
.scope(this)
.build();
}
public FooScopeImpl() {
this(new Dependencies() {});
}
public interface Dependencies {
}
@DaggerScope
@dagger.Component(
dependencies = Dependencies.class,
modules = Module.class
) …
```
=> Make ScopeImpl.Module static and abstract.

compiler/build.gradle
Test input directory was incorrect after module refactoring. This change allows correct invalidation of the compiler test task.
=> Fix compiler test inputs.

compiler/src/test/java/license/LicenseTest.kt, core/src/main/kotlin/motif/models/errors/MotifError.kt, core/src/main/kotlin/motif/models/motif/dependencies/DynamicDependency.kt
Previous LicenseTest implementation relied on hardcoded module directories and was unsurprisingly out of date. Update the logic to no longer use hardcoded paths and identify source directories by name (`src`) and existence of a sibling `build.gradle` file.
=> Fix license test.

compiler/ast/src/main/kotlin/motif/ast/compiler/CompilerType.kt, tests/src/main/java/testcases/E042_binds_invalid_wildcard_extends/A.java, tests/src/main/java/testcases/E042_binds_invalid_wildcard_extends/Scope.java, tests/src/main/java/testcases/E042_binds_invalid_wildcard_extends/Test.java, tests/src/main/java/testcases/E043_binds_invalid_wildcard_super/A.java, tests/src/main/java/testcases/E043_binds_invalid_wildcard_super/Scope.java, tests/src/main/java/testcases/E043_binds_invalid_wildcard_super/Test.java, tests/src/main/java/testcases/T051_binds_interface/A.java, tests/src/main/java/testcases/T051_binds_interface/B.java, tests/src/main/java/testcases/T051_binds_interface/Scope.java, tests/src/main/java/testcases/T051_binds_interface/Test.java, tests/src/main/java/testcases/T052_binds_interface_generic/A.java, tests/src/main/java/testcases/T052_binds_interface_generic/B.java, tests/src/main/java/testcases/T052_binds_interface_generic/Scope.java, tests/src/main/java/testcases/T052_binds_interface_generic/Test.java, tests/src/main/java/testcases/T053_binds_bounded_type_parameters/A.java, tests/src/main/java/testcases/T053_binds_bounded_type_parameters/B.java, tests/src/main/java/testcases/T053_binds_bounded_type_parameters/Scope.java, tests/src/main/java/testcases/T053_binds_bounded_type_parameters/Test.java, tests/src/main/java/testcases/T054_binds_wildcards/A.java, tests/src/main/java/testcases/T054_binds_wildcards/B.java, tests/src/main/java/testcases/T054_binds_wildcards/Scope.java, tests/src/main/java/testcases/T054_binds_wildcards/Test.java
Support for binding to interface types with binds factory methods.
=> Regression fix: Binds factory method w/ interface

compiler2/README.md, compiler2/build.gradle, compiler2/gradle.properties, compiler2/src/main/kotlin/motif/compiler/Component.kt, compiler2/src/main/kotlin/motif/compiler/ComponentBuilder.kt, compiler2/src/main/kotlin/motif/compiler/Dependencies.kt, compiler2/src/main/kotlin/motif/compiler/Module.kt, compiler2/src/main/kotlin/motif/compiler/ObjectsImpl.kt, compiler2/src/main/kotlin/motif/compiler/Processor.kt, compiler2/src/main/kotlin/motif/compiler/ScopeImpl.kt, compiler2/src/main/kotlin/motif/compiler/Util.kt, compiler2/src/main/resources/META-INF/services/javax.annotation.processing.Processor, settings.gradle
This is the top-level module for the Motif annotation processor. It contains the `Processor` itself and all code generation logic. The module will also run the Dagger annotation processor.
Tests will be added in a following PR.
=> Add codegen logic for new Motif compiler.

compiler2/src/test/java/com/google/testing/compile/MotifTestCompiler.java, compiler2/src/test/java/license/LicenseTest.kt, compiler2/src/test/java/motif/compiler/CompilationClassLoader.java, compiler2/src/test/java/motif/compiler/NamesTest.java, compiler2/src/test/java/motif/compiler/TestHarness.java
This test harness runs all of the existing integration tests in the `:tests` module. For error cases, instead of running the existing `Test.java` code, this new harness ensures that the output matches the content of the ERROR.txt file that exists in the test case directory.
=> Add new Motif compiler test harness

compiler/src/main/java/motif/compiler/Processor.kt, compiler2/src/main/kotlin/motif/compiler/Processor.kt, tests/compiler/src/main/java/motif/stubcompiler/StubProcessor.kt, tests/src/main/java/testcases/T056_deferred_rounds/Child.java, tests/src/main/java/testcases/T056_deferred_rounds/Scope.java, tests/src/main/java/testcases/T056_deferred_rounds/Test.java
Previously, Motif's annotation processor would fail to recognize code generated superinterfaces/superclasses. Leverage BasicAnnotationProcessor to defer processing of elements that depend on generated code. Only add test for immediate superinterfaces for now. Once google/auto#733 lands and is deployed we'll update to the newest version of google/auto and add tests for grandparent superinterfaces.
=> Defer processing of elements that depend on generated code.

compiler2/src/main/kotlin/motif/compiler/Util.kt, tests/src/main/java/testcases/T057_generic_dynamic_dependency/Child.java, tests/src/main/java/testcases/T057_generic_dynamic_dependency/Scope.java, tests/src/main/java/testcases/T057_generic_dynamic_dependency/Test.java
New annotation processor would previously crash with generic child method parameters.
=> Handle generic child method parameters.

compiler/src/main/java/motif/compiler/codegen/ChildMethodFactory.kt, compiler/src/main/java/motif/compiler/codegen/JavaPoetUtil.kt, compiler/src/main/java/motif/compiler/codegen/ModuleFactory.kt
This PR makes a few tweaks to the old codegen logic to match the new codegen exactly. After these changes, the old and new compiler generate exactly the same code in the Uber monorepo.
* Do not include qualifiers on overidden child dependencies methods.
* Source `@Provides` method parameter is always named "source".
* Use default constructor for child Scope construction if possible.
=> Tweak old codegen to match new implementation

compiler2/src/main/kotlin/motif/compiler/Component.kt, compiler2/src/main/kotlin/motif/compiler/ScopeImpl.kt, core2/src/main/kotlin/motif/core/ResolvedGraph.kt, core2/src/main/kotlin/motif/core/ScopeGraph.kt
The field  `private val parents: Map<Scope, List<Child>> ` in `ScopeGraph` stores the parents of a Scope while the class name `Child` could be ambiguous. Renaming `Child` class to `ScopeEdge` so that the name explicitly describes the responsibilities of the class `ScopeEdge` - to represent the relationships between parent and child scopes and to store additional information such as `child methods`.
=> Renames Child in ScopeGraph to ScopeEdge.

ast/src/main/kotlin/motif/ast/IrClass.kt, compiler/ast/src/main/kotlin/motif/ast/compiler/CompilerClass.kt, compiler/ast/src/test/kotlin/motif/ast/compiler/CompilerClassTest.kt, intellij/ast/src/main/kotlin/motif/ast/intellij/IntelliJClass.kt, intellij/ast/src/test/kotlin/motif/ast/intellij/IntelliJClassTest.kt
* Propagate generics information across multiple parent classes
* Handle `java.lang.Object`
=> Fixes to superclass implementation

compiler/src/main/kotlin/motif/compiler/CodeGenerator.kt, compiler/src/main/kotlin/motif/compiler/Processor.kt, compiler/src/main/kotlin/motif/compiler/ScopeImpl.kt, core/src/main/kotlin/motif/core/ResolvedGraph.kt, core/src/main/kotlin/motif/core/ScopeGraph.kt
Processor consumes `GeneratedClass` objects instead of `ScopeImpl` directly. This will allow us to generate classes other than just `ScopeImpl`s.
=> Add GeneratedClass abstraction to codegen logic.

CHANGELOG.md, ast/src/main/kotlin/motif/ast/IrMethod.kt, compiler/ast/src/main/kotlin/motif/ast/compiler/CompilerMethod.kt, compiler/src/main/kotlin/motif/compiler/Dependencies.kt, intellij/ast/src/main/kotlin/motif/ast/intellij/IntelliJMethod.kt
**Description**: This is a draft implementation of what is suggested on issue #33. It adds Javadoc comments for scope dependencies, mostly for traceability.
I had to add a little bit of hack to make constructors be formatted properly for Javadoc (checking if method name == `<init>`), there might be a way to improve this that I'm not seeing.
Also had to use fully qualified type names for all constructor params so Intellij would index it properly (e.g cmd+click-_able_)
**Related issue(s)**: #33
Changes on Dependencies.kt are be covered by current unit tests, but we could add new tests based on output matching (like the error tests). What do you think?
Screenshot of output (taken from slightly modified sample app):
=> Adding javadoc for Dependencies classes

compiler/src/main/kotlin/motif/compiler/Processor.kt, compiler/src/main/kotlin/motif/compiler/codegenv2/ScopeImplFactory.kt, compiler/src/test/java/com/google/testing/compile/MotifTestCompiler.java
`motif.mode=dagger` generates Dagger-based implementation
`motif.mode=java` generates the pure Java implementation
The default has also been updated to use the pure Java implementation.
=> Use `motif.mode` option to control code generation modes.

compiler/src/main/kotlin/motif/compiler/Names.kt, compiler/src/test/java/motif/compiler/NamesTest.java
**Before**
```
javax.lang.model.element.UnknownElementException: Unknown element:    
```
**After**
```
java.lang.IllegalStateException: Could not generate name for ErrorType: DoesNotExist. Check your code for missing imports or typos.
```
=> Throw better exception when generating names for ErrorTypes.

CHANGELOG.md, models/src/main/kotlin/motif/models/Scope.kt
Do not use computeIfAbsent in ScopeFactory in order to avoid ConcurrentModificationException in the IntelliJ plugin
=> Fix concurrent modification exception

CHANGELOG.md, compiler/src/main/kotlin/motif/compiler/ScopeImplFactory.kt, core/src/main/kotlin/motif/core/ResolvedGraph.kt, core/src/main/kotlin/motif/core/ScopeGraph.kt, models/src/main/kotlin/motif/models/Scope.kt
Allow graph processing to proceed even when a ParsingError is encountered. When we encounter a malformed Scope, it is marked as an ErrorScope. Children of ErrorScopes are treated as roots.
=> Allow graph processing to proceed even when a ParsingError is encountered

CHANGELOG.md, ast/src/main/kotlin/motif/ast/IrAnnotated.kt, ast/src/main/kotlin/motif/ast/IrAnnotation.kt, compiler/ast/src/main/kotlin/motif/ast/compiler/CompilerAnnotation.kt, errormessage/src/main/kotlin/motif/errormessage/InvalidQualifierHandler.kt, intellij/ast/build.gradle, intellij/ast/src/main/kotlin/motif/ast/intellij/IntelliJAnnotation.kt, intellij/ast/src/test/kotlin/motif/ast/intellij/IntelliJAnnotationTest.kt, intellij/ast/src/test/kotlin/motif/ast/intellij/IntelliJKotlinTest.kt, intellij/build.gradle, intellij/src/main/resources/META-INF/plugin.xml, intellij/src/test/kotlin/motif/intellij/TestHarness.kt, models/src/main/kotlin/motif/models/ParsingError.kt, models/src/main/kotlin/motif/models/Spread.kt, models/src/main/kotlin/motif/models/Type.kt
The IntelliJ plugin was failing due to unexpected behavior when processing implicit nullability annotations added to Kotlin parameters. This change allows us to handle annotations even if they don't exist on the classpath.
=> Handle implicit Kotlin nullability annotations.

core/src/main/kotlin/motif/core/ResolvedGraph.kt, core/src/main/kotlin/motif/core/State.kt
These new APIs will enable a "Find Motif usages" action in the IntelliJ plugin.
=> Add ResolvedGraph.getSinks(IrType) and ResolvedGraph.getSources(IrType) APIs

core/src/main/kotlin/motif/core/ResolvedGraph.kt
`ResolvedGraph.getSinks` and `ResolvedGraph.getSources` will now return an empty set if the given type does not exist in the graph.
=> Fix NPE for getSinks and getSources

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/ScopeHierarchyUtils.kt, intellij/src/main/kotlin/motif/intellij/actions/MotifUsageAction.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyTreeStructure.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/UsageHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyUsageSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyUsageSinksSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyUsageSourcesSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/ui/MotifUsagePanel.kt, intellij/src/main/resources/META-INF/plugin.xml
This diff adds the ability to search for usage of a given class in the motif graph. It opens a separate tab within the IntelliJ plugin main window, with the list of places for an object of the supplied class types are produces and consumed.
=> [IntelliJ Plugin] Add support for Search Usage feature

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/provider/ScopeNavigationLineMarkerProvider.kt
Display a listbox whenever scope has multiple parents, to let developers pick which parent she wants to navigate to.
=> Support for navigating to parent scope w/ multiple parents

intellij/src/main/kotlin/motif/intellij/GraphFactory.kt, intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/actions/MotifGraphAction.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyRootScopeNodeDescriptor.kt, intellij/src/main/kotlin/motif/intellij/provider/ScopeHierarchyLineMarkerProvider.kt, intellij/src/main/resources/META-INF/plugin.xml
- Change behavior so that user currently has to explicitly refresh the graph in order to use the plugin.
- Update missing icon in menus
- Remove necessary logging code
Detecting plugin window opening (and compute initial graph automatically) would require refactoring to use [ToolWindowFactory](https://www.jetbrains.org/intellij/sdk/docs/user_interface_components/tool_windows.html)
=> Avoid IDE startup slowdown by not computing graph on plugin startup, add missing icons

errormessage/src/main/kotlin/motif/errormessage/ErrorHandler.kt, errormessage/src/main/kotlin/motif/errormessage/ErrorMessage.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyTreeStructure.kt
Graph parameter was never used by getting ErrorMessage, it may be a left-over. All usages show that error list is retrieved from graph and iterated on to call `ErrorMessage.get`. Also by API, it makes more sense that `get` function receives and MotifError and returns a corresponding ErrorMessage.
=> Remove unused graph parameter from ErrorMessage

intellij/src/main/kotlin/motif/intellij/hierarchy/ErrorHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/HierarchyBrowserBase.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopePropertyHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/UsageHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyDependenciesSectionDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyDependencyDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyErrorDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchyScopeDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySimpleDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySinkDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourceDescriptor.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/descriptor/ScopeHierarchySourcesAndSinksSectionDescriptor.kt
This PR is specifying search terms used for string matching for the various nodes in browser hierarchy. 
It also turn on searching on nodes that are not expanded yet.
=> Add search support for the various UI components used in plugin UI

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/ScopeHierarchyUtils.kt, intellij/src/main/kotlin/motif/intellij/actions/MotifGraphAction.kt, intellij/src/main/kotlin/motif/intellij/actions/MotifUsageAction.kt
Currently, the menu is grayed out whenever the graph hasn’t been computed. 
This PR changes behavior to have these active all the time, and when menu items are selected while graph hasn’t been computed, we go ahead and compute it and resume menu action.
=> Decrease barrier of entry for contextual menu

intellij/ast/src/main/kotlin/motif/ast/intellij/IntelliJClass.kt, intellij/ast/src/main/kotlin/motif/ast/intellij/IntelliJType.kt, intellij/ast/src/test/kotlin/motif/ast/intellij/IntelliJAnnotationTest.kt, intellij/ast/src/test/kotlin/motif/ast/intellij/IntelliJClassTest.kt, intellij/src/main/kotlin/motif/intellij/GraphFactory.kt
In large repositories, it's not uncommon for the IDE to be unable to index some types involved in the DI graph. Previously, we would just blow up with an exception in these cases. This PR allows IntelliJ graph processing to proceed even in the presence of an unknown type. This strategy can lead to unexpected behavior in these cases but seems like a reasonable alternative to crashing the plugin.
=> Make IntelliJ plugin more resilient to unknown types

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/analytics/AnalyticsProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopePropertyHierarchyBrowser.kt, intellij/src/main/kotlin/motif/intellij/ui/MotifScopePanel.kt
- stop overriding method whose modifiers changed (see https://github.com/JetBrains/intellij-community/commit/e8c2d857b777cd36f72626d869800a2ad848cab8). The alternate fix to the focus issue is to tear down and rebuild the scope property browser swing component, instead of updating it.
- don't use getHierarchyBase() API on browser UI component : this API only exists in IJ 2019+
- try/catch use of extension point API : it throws on 2018.x so we don't want that in a static initializer
=> Fixes to enable Motif Plugin to work on IJ 2018.x

intellij/src/main/kotlin/motif/intellij/analytics/AnalyticsProjectComponent.kt
Use 2018-compatible API to query custom extension points
=> Use 2018-compatible API to query custom extension points

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt
This is to avoid bug when content doesn't get updated when multiple window of these types are opened simultaneously.
=> Treat usage/ancrestor tabs as singleton

intellij/src/main/kotlin/motif/intellij/MotifProjectComponent.kt, intellij/src/main/kotlin/motif/intellij/PsiUtils.kt, intellij/src/main/kotlin/motif/intellij/provider/ScopeNavigationLineMarkerProvider.kt, intellij/src/main/resources/META-INF/plugin.xml
* Register `ScopeNavigationLineMarkerProvider` for Kotlin.
* Update `ScopeNavigationLineMarkerProvider` to support both Kotlin and Java.
The existing line markers does not support Kotlin, this pull request adds Kotlin support for `ScopeNavigationLineMarkerProvider` which enables to navigate to parent/child scopes through gutter icons. 
https://github.com/uber/motif/issues/192
=> Scope navigation line markers kotlin support

build.gradle, gradle/dependencies.gradle, settings.gradle
There's still one missing dependency required to be in Maven Central (tracked [here](https://youtrack.jetbrains.com/issue/IDEA-261387)). To remove Jitpack, I made a minor version bump
=> Remove Jitpack and remove jCenter

compiler/src/main/kotlin/motif/compiler/Names.kt
There is an edge case where motif would generate dependencies method names of inner classes with a "$" in the method name which could lead to compilation errors.
This simple one line fix will make sure that inner classes that have not been fully resolved by the compiler will be resolved and update their fullName property which is effecting the simpleName value used to generate the method names.
In our case pre compiled class files are passed to the javac classpath, for inner classes the java compiler may resolve the fully qualified name and build the names table in multiple passes.
1. In the first step it will create inner classes with the $, given this is how they are represented in the class file (for example A$B) 
Below is a stacktrace example
```formFullName:745, Symbol$TypeSymbol …
```
=> Fix wrong method names generation

compiler/ast/src/main/kotlin/motif/ast/compiler/CompilerType.kt
**Context**:
This is follow up commit to 6a2e7821ae6ffd41e8bae692a00bb498f9c3541b which should fix another edge case of Motif unable to find a dependency method of inner classes types given their full name value in javac is represented with $.
[ScopeFactoryImpl](https://github.com/uber/motif/blob/0.3.6/compiler/src/main/kotlin/motif/compiler/ScopeImplFactory.kt#L318
) is doing a lookup for a method based on the given Type.
The [methodByType](https://github.com/uber/motif/blob/0.3.6/models/src/main/kotlin/motif/models/Dependencies.kt#L42) map is using  [TreeMap](https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html) implementation where keys are matched based on Type's [compareTo](https://github.com/uber/motif/blob/0.3.6/models/src/main/kotlin/motif/models/Type.kt#L38) method, …
=> Fix unable to find dependency method

gradle/dependencies.gradle, samples/sample/build.gradle, samples/sample/src/main/AndroidManifest.xml, samples/sample/src/main/java/motif/sample/app/root/RootActivity.java, samples/sample/src/main/java/motif/sample/app/root/RootController.java, samples/sample/src/main/java/motif/sample/app/root/RootFactory.java, samples/sample/src/main/java/motif/sample/app/root/RootScope.java, samples/sample/src/test/java/motif/sample/app/root/RootScopeTest.java
Currently, whenever you open the motif sample app, it shows an empty screen. This is because the sample app did not handle the SD card read permission tasks. This pull request will fix the issue by leveraging the `ActivityResultContracts` to initialize the permission request process and automatically load the photos whenever the permission is granted. This way, the sample app will run seamlessly with intuitive functions.
No motif library code changes.
=> Fix samples app not loading any data due to SD card request permission issues.

.github/workflows/ci.yml, build.gradle, compiler/ast/src/main/kotlin/motif/ast/compiler/CompilerType.kt, compiler/src/test/java/motif/compiler/NamesTest.kt, compiler/src/test/java/motif/compiler/ProGuard.kt, compiler/src/test/resources/default.pro, gradle/dependencies.gradle, intellij/ast/build.gradle, intellij/build.gradle, intellij/testing/build.gradle, tests/src/main/java/testcases/T071_scope_factory/config.pro, tests/src/main/java/testcases/T072_scope_factory/config.pro, tests/src/main/java/testcases/T073_scope_factory_no_dependencies/config.pro, tests/src/main/java/testcases/T074_superclass_nested_class/config.pro, tests/src/main/java/testcases/T075_scope_factory_unused_dependencies/config.pro
Run tests using Java 11 and ajdust CompilerType's qualified name since TypeMirror's toString includes type annotations
=> Use Java 11 for CI

RELEASING.md, build.gradle, gradle.properties, gradle/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, intellij/src/main/kotlin/motif/intellij/hierarchy/ScopeHierarchyBrowser.kt, settings.gradle, xprocessing-testing/build.gradle, xprocessing-testing/gradle.properties, xprocessing/build.gradle, xprocessing/gradle.properties
This PR updates some libraries and adds KSP & [XProcessing](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler-processing/README.md) (a wrapper around AP & KSP APIs) so we can add support for KSP (#211). Two new Gradle modules were added to provide the shaded version of xprocessing per the recommendation of the AndroidX team to avoid conflicts with Room.
=> Add KSP & XProcessing deps

build.gradle, compiler/build.gradle, compiler/ksp/build.gradle, compiler/ksp/gradle.properties, compiler/ksp/src/main/kotlin/com/google/devtools/ksp/KspErrorThrower.kt, compiler/ksp/src/main/kotlin/motif/compiler/ksp/MessageWatcher.kt, compiler/ksp/src/main/kotlin/motif/compiler/ksp/MotifSymbolProcessorProvider.kt, compiler/ksp/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider, compiler/src/main/kotlin/motif/compiler/MotifProcessingStep.kt, settings.gradle
This adds a new Motif KSP compiler artifact, a SymbolProcessingProvider (entry point for KSP), and a placeholder `XProcessingStep` to work towards #211. The step will have logic ported over from the AP processor and its APIs which will then enable AP & KSP to work.
=> Add KSP module, processor, and placeholder step

compiler/ast/build.gradle, compiler/ast/src/main/kotlin/com/uber/xprocessing/ext/XAnnotation.kt, compiler/ast/src/main/kotlin/com/uber/xprocessing/ext/XElement.kt, compiler/ast/src/main/kotlin/com/uber/xprocessing/ext/XOverrides.kt, compiler/ast/src/main/kotlin/com/uber/xprocessing/ext/XProcessingEnv.kt, compiler/ast/src/main/kotlin/com/uber/xprocessing/ext/XType.kt, compiler/ast/src/main/kotlin/com/uber/xprocessing/ext/XTypeElement.kt, compiler/ast/src/main/kotlin/com/uber/xprocessing/ext/XTypeUtils.kt, compiler/ast/src/main/kotlin/motif/ast/compiler/CompilerClass.kt
Adds various utilities that will be needed in #211. Most extension functions are porting AutoCommon logic to XProcessing APIs or fixing inconsistencies in toString() behavior between the JAVAC and KSP backends.
=> Add utilities for Motif KSP using XProcessing

compiler/build.gradle, compiler/ksp/build.gradle, compiler/ksp/src/main/kotlin/motif/compiler/ksp/MessageWatcher.kt, compiler/ksp/src/main/kotlin/motif/compiler/ksp/MotifSymbolProcessorProvider.kt, compiler/src/main/kotlin/motif/compiler/JavaCodeGenerator.kt, compiler/src/main/kotlin/motif/compiler/MotifProcessingStep.kt, compiler/src/main/kotlin/motif/compiler/XFunSpec.kt, compiler/src/main/kotlin/motif/compiler/XNameVisitor.kt
Adds two utilities for Kotlin codegen using XProcessing APIs that will be needed in #211 . The first is a port of `MethodSpec.overrides` from JavaPoet and the second is a port of `javax.lang.model.util.SimpleTypeVisitor` for generating var and fun names.
=> Add XProcessing utils for codegen

compiler/ast/src/test/kotlin/motif/ast/compiler/CompilerClassTest.kt, compiler/src/main/kotlin/motif/compiler/CodeGenerator.kt, compiler/src/main/kotlin/motif/compiler/Processor.kt, compiler/src/main/kotlin/motif/compiler/XNameVisitor.kt, compiler/src/test/java/motif/compiler/NamesTest.kt, compiler/src/test/java/motif/compiler/TestParameters.kt
Migrate all test classes and utils except for TestHarness to use XProcessing APIs for #211
=> Migrate test classes to XProcessing APIs

ast/build.gradle, build.gradle, compiler/ast/build.gradle, compiler/build.gradle, core/build.gradle, errormessage/build.gradle, gradle/dependencies.gradle, intellij/ast/build.gradle, intellij/build.gradle, models/build.gradle, viewmodel/build.gradle
Similar to the series of simple-store pull requests https://github.com/uber/simple-store/pull/96, https://github.com/uber/simple-store/pull/97, and https://github.com/uber/simple-store/pull/98.
This pull request updates our document publishing flows such that when we update kotlin to 1.9+ in motif, we can still build/publish changes.
=> Update Dokka to Support Kotlin 1.9

build.gradle, samples/sample/build.gradle, settings.gradle, tests/build.gradle
This pull request addresses an omission in https://github.com/uber/motif/pull/262, where we'd attempt to generate documents even for sample and test modules, which are not published.
In doing so, we noticed an opportunity to make the naming pattern more consistent for all nested modules in the project - namely, the `:compiler:ast` is `compiler-ast` (we figured it's for ease of publication), but despite the `samples` and `tests` modules being unpublished, unifying the naming pattern could make it look/feel more consistent and make preventing document generation a bit easier.
=> Unify tests/samples naming pattern
